spring:
  profiles:
    active: local

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

app:
  jwt:
    secret: ${JWT_SECRET}
    access-expiration: 1800000      # 30분
    refresh-expiration: 604800000   # 7일

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  metrics:
    tags:
      application: donggree